### ISSUE TITLE
[bug] amrfinder database version

### ISSUE THREAD

**Issue by telatin** [bactopia/bactopia#206] opened 2021-03-19 14:05 UTC
**Description**
AMR finder fails complaining about the database version:
```
  Running: amrfinder -n AF01.ffn -d amrfinderdb/ -o antimicrobial-resistance/AF01-gene-report.txt --ident_min -1 --coverage_min 0.5 --translation_table 11 --threads 4
  Software directory: '/qi/tools/miniconda3/envs/bactopia/share/bactopia-1.6.x/conda/envs/antimicrobial_resistance-1.6.x/bin/'
  Software version: 3.9.8
  Database directory: 'amrfinderdb'
  Database version: 2021-03-01.1
  
  *** ERROR ***
  Database requires sofware version at least 3.10.1
  To download the latest version to the default directory run: amrfinder -u
```

**Steps to Reproduce**
```
bactopia datasets --species "Klebsiella pneumoniae" --include_genus --limit 100 --outdir Kpn
bactopia prepare $DIRNAME > file_list
bactopia --fastqs file_list --outdir ${DIRNAME}_out --datasets Kpn/ --species "Klebsiella pneumoniae"
```

**Expected Behavior**
A description of what is expected to happen.

**Execution Environment**

- Bactopia Version: **bactopia 1.6.1**
- OS: **"Ubuntu 16.04.4 LTS"**
- Environment: Ubuntu VM with Conda
 
**Additional Information**
Hello @rpetit3 ! 
I'm sorry to keep pestering with issues, but I'd love to have bactopia up and running. I don't have much experience in running it so maybe I'm doing something wrong.

**Comment by rpetit3** [comment] 2021-03-19 14:10
Not a problem at all! 

Looks like AMRFinder+ is making some changes, is starting to associate DB to program version more often now. Haha they got me right around ~v1.6.0 last time

I'm going to get this fixed today (as well as your other one) and push a version update.

**Comment by telatin** [comment] 2021-03-19 14:16
Many thank for this incredibly quick reply :) 
Do you have a recommended "stable" release to get started?

**Comment by rpetit3** [comment] 2021-03-19 15:19
This will be fixed the next version (v1.6.2), but it doesn't fix the root cause. Will push update once CI passes

I've reached out to the AMRFinder+ team (https://github.com/ncbi/amr/issues/51) to see if there are alternatives methods to deal with this.

**Comment by rpetit3** [comment] 2021-03-19 18:59
I released v1.6.2, and it should be available on Bioconda soon.

So here's what happened. I use AMRFinder+ in two spots with bactopia. The version of AMRFinder+ that downloaded the database (`bactopia datasets`) was not the same version used in the Bactopia analysis. 

I'm going to start thinking of a more permanent solution, but v1.6.2 should resolve this issue for the time being.

Going to close for now, but please feel free to reopen!

**Closed by rpetit3** 2021-03-19 18:59 UTC
Labels: bug

**Comment by gabimuir** [comment] 2021-10-05 15:47
I seem to be having this problem now, this time requiring amrfinder software version 3.10.16

```
Command error:
  Running: amrfinder -n SRX4563634.ffn -d amrfinderdb/ -o antimicrobial-resistance/SRX4563634-gene-report.txt --ident_min -1 --coverage_min 0.5 --translation_table 11 --threads 4
  Software directory: '/home/gabi/.conda/envs/bactopia_new/share/bactopia-1.7.x/conda/envs/antimicrobial_resistance-1.7.x/bin/'
  Software version: 3.10.1
  Database directory: 'amrfinderdb'
  Database version: 2021-09-30.1
  
  *** ERROR ***
  Database requires sofware version at least 3.10.16
  To download the latest version to the default directory run: amrfinder -u
```

Is there a way to manually downgrade the amrfinderdb to quickly fix the problem? Or a way to bypass the amrfinder step?

**Comment by rpetit3** [comment] 2021-10-05 16:04
You should be able to skip this step using `--skip_amr`

I'll work on improving this in v2
