### ISSUE TITLE
bactopia datasets

### ISSUE THREAD

**Issue by AyshaSezmis** [bactopia/bactopia#185] opened 2021-01-07 07:21 UTC
Dear Robert,

First of all many thanks for providing us with such an amazing pipeline :). I have installed bactopia using conda to my MacOS Big Sur. It looks like it has installed everything properly. 

I wanted to start with the Tutorial provided. However, batopia datasets doesn't seem to be working in my machine. Hence I couldn't continue. When I type bactopia datasets in my command line, i get the following error message:

(bactopia) MU00102102X:~ asez0001$ bactopia datasets
Traceback (most recent call last):
  File "/Users/asez0001/miniconda3/envs/bactopia/bin/bactopia-datasets.py", line 122, in <module>
    from executor import ExternalCommand, ExternalCommandFailed
ModuleNotFoundError: No module named 'executor'

Same thing when I type bactopia datasets --help

(bactopia) MU00102102X:~ asez0001$ bactopia datasets --help
Traceback (most recent call last):
  File "/Users/asez0001/miniconda3/envs/bactopia/bin/bactopia-datasets.py", line 122, in <module>
    from executor import ExternalCommand, ExternalCommandFailed
ModuleNotFoundError: No module named 'executor'
(bactopia) MU00102102X:~ asez0001$ 

On the other hand, when I type bactopia, the help menu appears on my terminal. So bactopia and all other usages such as prepare, search and tools, all seem to work with their help menus appearing.

I would love to use this really amazing pipeline in my research (studying horizontal gene transfer of antimicrobial resistance using Acitinobacter species) if possible. 

Any help will be much appreciated. 
Many thanks in advance :).
Best,
Aysha

**Comment by rpetit3** [comment] 2021-01-07 12:33
Hi  Aysha!

Thank you very much! Let's see if we can git this figured out.

What are the outputs of the following?
```
which bactopia
which python
```

**Comment by AyshaSezmis** [comment] 2021-01-07 13:14
Hi Robert,

Thank you so much for your quick reply :).

These are the results for the following commands:

(bactopia) MU00102102X:~ asez0001$ which bactopia
/Users/asez0001/miniconda3/envs/bactopia/bin/bactopia
(bactopia) MU00102102X:~ asez0001$ which python
/Users/asez0001/miniconda3/envs/bactopia/bin/python
(bactopia) MU00102102X:~ asez0001$

**Comment by rpetit3** [comment] 2021-01-07 13:36
Those look good, maybe also these:

```
which python3

conda env export
```

**Comment by AyshaSezmis** [comment] 2021-01-07 19:55
Thank you Robert,

Sorry I am in Australia and different time zone hence my late reply. Below are the results for those two :)

(bactopia) MU00102102X:~ asez0001$ which python3
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3

(bactopia) MU00102102X:~ asez0001$ conda env export
name: bactopia
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - ariba=2.14.6=py36h043d725_0
  - bactopia=1.5.5=0
  - bcftools=1.8=h4da6232_3
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - biopython=1.78=py36h7b4949f_1
  - blast=2.6.0=boost1.64_2
  - bowtie2=2.3.5.1=py36h2dec4b4_0
  - brotlipy=0.7.0=py36ha3de816_1001
  - bzip2=1.0.8=hc929b4f_4
  - c-ares=1.17.1=hc929b4f_0
  - ca-certificates=2020.12.5=h033912b_0
  - capnproto=0.6.1=h0ceac7d_2
  - cd-hit=4.8.1=hd9629dc_0
  - certifi=2020.12.5=py36h79c6626_1
  - cffi=1.14.4=py36hfe0777f_1
  - chardet=4.0.0=py36h79c6626_0
  - coloredlogs=15.0=py36h79c6626_0
  - conda=4.9.2=py36h79c6626_0
  - conda-package-handling=1.7.2=py36ha3de816_0
  - coreutils=8.31=h0b31af3_0
  - cryptography=3.3.1=py36hd858a44_0
  - curl=7.71.1=hcb81553_8
  - cycler=0.10.0=py_2
  - dendropy=4.5.1=pyh3252c3a_0
  - enum34=1.1.10=py36h9f0ad1d_2
  - executor=23.2=pyhd3deb0d_0
  - fasteners=0.14.1=py_3
  - freetype=2.10.4=h3f75d11_0
  - gettext=0.19.8.1=h7937167_1005
  - gsl=2.6=h71c5fe9_1
  - humanfriendly=9.1=py36h79c6626_0
  - icu=68.1=h74dc148_0
  - idna=2.10=pyh9f0ad1d_0
  - jpeg=9d=hbcb3906_0
  - kiwisolver=1.3.1=py36he46ecad_0
  - krb5=1.17.2=h60d9502_0
  - lcms2=2.11=h11f7e16_1
  - libblas=3.9.0=7_openblas
  - libcblas=3.9.0=7_openblas
  - libcurl=7.71.1=h9bf37e3_8
  - libcxx=11.0.0=h4c3b8ed_1
  - libdeflate=1.0=h1de35cc_1
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.3=h046ec9c_2
  - libgfortran=5.0.0=h6c81a4c_15
  - libgfortran5=9.3.0=h6c81a4c_15
  - libiconv=1.16=haf1e3a3_0
  - libidn2=2.3.0=h0b31af3_0
  - liblapack=3.9.0=7_openblas
  - libnghttp2=1.41.0=h7580e61_2
  - libopenblas=0.3.12=openmp_h54245bb_1
  - libpng=1.6.37=h7cec526_2
  - libssh2=1.9.0=h8a08a2b_5
  - libtiff=4.2.0=h355d032_0
  - libunistring=0.9.10=h1de35cc_0
  - libwebp-base=1.1.0=hbcb3906_3
  - libxml2=2.9.10=h802ca4f_3
  - libxslt=1.1.33=h5739fc3_2
  - llvm-openmp=11.0.0=h73239a0_1
  - lxml=4.6.2=py36ha579a0c_0
  - lz4-c=1.9.3=h046ec9c_0
  - mash=2.2.2=h194473e_2
  - matplotlib-base=3.3.3=py36h50af36e_0
  - monotonic=1.5=py_0
  - mummer=3.23=h6de7cb9_11
  - ncbi-genome-download=0.3.0=pyh864c0ab_1
  - ncurses=6.2=h2e338ed_4
  - nextflow=20.10.0=hecda079_0
  - numpy=1.19.5=py36h08dc641_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjdk=11.0.8=hb0a8c7a_0
  - openssl=1.1.1i=h35c211d_0
  - perl=5.32.0=hbcb3906_0
  - pillow=8.1.0=py36hc04f27d_0
  - pip=20.3.3=pyhd8ed1ab_0
  - property-manager=3.0=py_0
  - pycosat=0.6.3=py36ha3de816_1005
  - pycparser=2.20=pyh9f0ad1d_2
  - pyfastaq=3.17.0=py_2
  - pymummer=0.10.3=py36_1
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysam=0.15.3=py36h726f235_1
  - pysocks=1.7.1=py36h2432673_2
  - python=3.6.12=h6c3b2c9_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - readline=8.0=h0678c8f_2
  - requests=2.25.1=pyhd3deb0d_0
  - ruamel_yaml=0.15.80=py36ha3de816_1003
  - samtools=1.4.1=0
  - sed=4.7=h3efe00b_1000
  - setuptools=49.6.0=py36h2432673_2
  - six=1.15.0=pyh9f0ad1d_0
  - soupsieve=2.0.1=py_1
  - spades=3.14.1=he641558_0
  - sqlite=3.34.0=h17101e1_0
  - tbb=2020.2=h926bf3e_2
  - tk=8.6.10=h0419947_1
  - tornado=6.1=py36h6941dd6_0
  - tqdm=4.55.1=pyhd8ed1ab_0
  - unzip=6.0=haf1e3a3_2
  - urllib3=1.26.2=pyhd8ed1ab_0
  - verboselogs=1.7=py_0
  - wget=1.20.1=h33e2efd_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=haf1e3a3_1
  - yaml=0.2.5=haf1e3a3_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.4.8=hf387650_1
prefix: /Users/asez0001/miniconda3/envs/bactopia

**Comment by rpetit3** [comment] 2021-01-07 20:10
Hey! We found our issue:

```
which python3
/Library/Frameworks/Python.framework/Versions/3.9/bin/python3
```

The wrong python3 is being called, we want `/Users/asez0001/miniconda3/envs/bactopia/bin/python3`.

What does the following command look like?
```
echo $PATH
```

**Comment by AyshaSezmis** [comment] 2021-01-07 20:22
Oh wow!! Thasts great news :))

(bactopia) MU00102102X:~ asez0001$ echo $PATH
/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/asez0001/miniconda3/envs/bactopia/bin:/Users/asez0001/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin

**Comment by rpetit3** [comment] 2021-01-07 20:46
Alright so the issue is this `/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin` is being put in front of `/Users/asez0001/miniconda3/envs/bactopia/bin`.

You will want to take a look at `~/.bash_profile` to see why Python is being put at the front. If you aren't familiar with the PATH here's a [tutorial](https://imstudio.medium.com/path-macos-best-practice-for-path-environment-variables-on-mac-os-35ec4076a486) (haha full disclaimer I quickly scanned it!).

If there isn't any personal info (I'm guessing not) and you feel comfortable posting the contents of your `.bash_profile` feel free to put it here. We can work together to get it figured out.

**Comment by AyshaSezmis** [comment] 2021-01-07 20:50
Awesome :))). Thank you so much :))) Yes, you are right, I am not familiar with computers at all to be honest :))

Here is the results of ~/.bash_profile

(bactopia) MU00102102X:~ asez0001$ ~/.bash_profile
-bash: /Users/asez0001/.bash_profile: Permission denied

It says permission denied. How do I get the permission, Robert?

**Comment by rpetit3** [comment] 2021-01-07 20:53
Ah, no worries! You just needed a `cat` in front:  `cat /Users/asez0001/.bash_profile`

Please just verify there's no credentials or personal info before posting. I don't think there will be but you never know!

**Comment by AyshaSezmis** [comment] 2021-01-07 20:54
There shouldn't be any personal info Robert :))) Thank you for your help. I really appreciate it :))

**Comment by AyshaSezmis** [comment] 2021-01-07 20:56
Results of that command :)))

(bactopia) MU00102102X:~ asez0001$ cat /Users/asez0001/.bash_profile

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/asez0001/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/asez0001/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/asez0001/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/asez0001/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


# Setting PATH for Python 3.9
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.9/bin:${PATH}"
export PATH

##
# Your previous /Users/asez0001/.bash_profile file was backed up as /Users/asez0001/.bash_profile.macports-saved_2020-12-23_at_13:30:30
##

# MacPorts Installer addition on 2020-12-23_at_13:30:30: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# MacPorts Installer addition on 2020-12-23_at_13:30:30: adding an appropriate DISPLAY variable for use with MacPorts.
export DISPLAY=:0
# Finished adapting your DISPLAY environment variable for use with MacPorts.

(bactopia) MU00102102X:~ asez0001$

**Comment by rpetit3** [comment] 2021-01-07 21:02
I think this should do it for you (I might have missed some comments).  Here's some info on [Markdown Code and Syntax Highlighting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting) to make things easier next time. (no worries though!)

All I did below is move the conda bit to the end so that that's the first thing in the PATH.

```
# Setting PATH for Python 3.9
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.9/bin:${PATH}"
export PATH

# our previous /Users/asez0001/.bash_profile file was backed up as /Users/asez0001/.bash_profile.macports-saved_2020-12-23_at_13:30:30
# MacPorts Installer addition on 2020-12-23_at_13:30:30: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

# Finished adapting your PATH environment variable for use with MacPorts.
# MacPorts Installer addition on 2020-12-23_at_13:30:30: adding an appropriate DISPLAY variable for use with MacPorts.
export DISPLAY=:0

# Finished adapting your DISPLAY environment variable for use with MacPorts.

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/asez0001/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
  eval "$__conda_setup"
else
  if [ -f "/Users/asez0001/miniconda3/etc/profile.d/conda.sh" ]; then
    . "/Users/asez0001/miniconda3/etc/profile.d/conda.sh"
  else
    export PATH="/Users/asez0001/miniconda3/bin:$PATH"
  fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

**Comment by AyshaSezmis** [comment] 2021-01-07 21:37
Thank you so much Robert :)).

May be I don't understand how to set this PATH from my end. Hence, it still isn't working for me. 

I will try and get help with our IT support here at Monash University.

Once again many thanks for your help :))

Best wishes,
Aysha

**Comment by rpetit3** [comment] 2021-01-07 21:51
No worries! Here it is a downloadable file: [bash_profile.txt](https://github.com/bactopia/bactopia/files/5784084/bash_profile.txt) 
 
If you download the file to your Desktop, you can do this in your terminal:
```
# Back up current profile
mv /Users/asez0001/.bash_profile /Users/asez0001/.bash_profile.backup

# replace current profile with downloaded profile
mv /Users/asez0001/Desktop/bash_profile .txt /Users/asez0001/.bash_profile
```

After doing that, keep the current terminal open, but also open up another terminal. Then try
```
echo $PATH
```
This should hopefully give a better path.



If there are any issues, you can go back to the original terminal and put the backup back.
```
mv  /Users/asez0001/.bash_profile.backup /Users/asez0001/.bash_profile
```


I agree with you, IT should be able to get you situated too!

Let me know if there's anything else I can do to help out.

**Comment by AyshaSezmis** [comment] 2021-01-07 22:06
Hi Robert,

This works :)))) This downloaded bash_profile.txt really changed things :))))

Thank you so much for your help.

I have just tried bactopia datasets again and the below is happening :))

(bactopia) MU00102102X:~ asez0001$ bactopia datasets
2021-01-08 09:01:33:root:INFO - Setting up Ariba datasets
2021-01-08 09:01:33:root:INFO - Setting up vfdb_core Ariba dataset

I am guessing it is setting up this for me now. I will leave it running and see what happens next.

Once again thank you so much for your help :))

Best wishes,
Aysha

**Comment by rpetit3** [comment] 2021-01-07 22:17
Yay! Enjoy your day!

**Comment by rpetit3** [comment] 2021-01-07 22:17
Also, going to close this for now, please feel free to reopen!

**Closed by rpetit3** 2021-01-07 22:17 UTC
