### ISSUE TITLE
[question] Process `BACTOPIA:DUMPSOFTWAREVERSIONS (1)` terminated with an error exit status (1)

### ISSUE THREAD

**Issue by cs-di05** [bactopia/bactopia#454] opened 2023-09-29 14:11 UTC
Hello, I am following the Bactopia Beginner's guide with my own ONT sequencing data. When executing the code `bactopia --sample S_Livi_MB4531 --ont path/to/S_Livi_MB4531.fastq.gz`, I receive an error message. Here is the [nextflow.log](https://github.com/bactopia/bactopia/files/12766417/nextflow.log) file. My system specifications can be found [here](https://github.com/bactopia/bactopia/files/12766423/specs.txt). How can I resolve this error? If more information is needed, please ask. Thanks in advance!

**Comment by rpetit3** [comment] 2023-09-29 14:14
Hello!

Thank you for reaching out!

Can you share a file called `versions.yml` in this directory `/home/cas/work/46/a1f5018bb4518713d1c5ee42ff5246` ?

Thank you!
Robert

**Comment by cs-di05** [comment] 2023-09-29 14:25
Thanks for the quick reply. I changed the format but here is the [versions file](https://github.com/bactopia/bactopia/files/12766637/versions.txt)

**Comment by rpetit3** [comment] 2023-09-29 15:07
Looking like the issue was caused by `fastq-dl`.

```
    fastq-dl: Traceback (most recent call last): File "/home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/bin/fastq-dl", line 6, in <module> from fastq_dl.fastq_dl import main File "/home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/lib/pypy3.9/site-packages/fastq_dl/fastq_dl.py", line 14, in <module> from pysradb import SRAweb File "/home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/lib/pypy3.9/site-packages/pysradb/__init__.py", line 8, in <module> from .filter_attrs import expand_sample_attribute_columns File "/home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/lib/pypy3.9/site-packages/pysradb/filter_attrs.py", line 5, in <module> import pandas as pd File "/home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/lib/pypy3.9/site-packages/pandas/__init__.py", line 22, in <module> from pandas.compat import is_numpy_dev as _is_numpy_dev # pyright: ignore # noqa:F401 File "/home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/lib/pypy3.9/site-packages/pandas/compat/__init__.py", line 25, in <module> from pandas.compat.numpy import ( File "/home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/lib/pypy3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module> from pandas.util.version import Version File "/home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/lib/pypy3.9/site-packages/pandas/util/__init__.py", line 2, in <module> from pandas.util._decorators import ( # noqa:F401 File "/home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/lib/pypy3.9/site-packages/pandas/util/_decorators.py", line 14, in <module> from pandas._libs.properties import cache_readonly File "/home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/lib/pypy3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module> from pandas._libs.interval import Interval TypeError: type 'cython_function_or_method' is not an acceptable base type
```

I'm going to see if I can replicate this and get a fix in place. Thank you for reporting this!

For the time being you can choose to ignore the error, as only the final file with the software versions is affected. Each sample will have version files for each of the steps

**Comment by egenomics** [comment] 2023-10-03 14:14
Hi,
I am having exactly the same problem:
```
[e7/910abb] process > BACTOPIA:DUMPSOFTWAREVERSIONS (1)                                  [100%] 4 of 4, failed: 4, retries: 3 ✘
ERROR ~ Error executing process > 'BACTOPIA:DUMPSOFTWAREVERSIONS (1)'

Caused by:
  Process `BACTOPIA:DUMPSOFTWAREVERSIONS (1)` terminated with an error exit status (1)

```
My versions.yml file looks like this:
```
"BACTOPIA:QC:QC_MODULE":
    bbduk: 39.01
    fastp: 0.23.4
    fastqc: 0.12.1
    fastq-scan: 1.0.1
    lighter: 1.1.2
    nanoplot: 1.41.6
    nanoq: 0.10.0
    pigz: 2.6
    porechop: 0.2.4
    rasusa: 0.7.1
"BACTOPIA:GATHER:GATHER_MODULE":
    art: 2.5.8
    fastq-dl: 2.0.4
    fastq-scan: 1.0.1
    ncbi-genome-download: 0.3.3
    pigz: 2.6
"BACTOPIA:AMRFINDERPLUS:AMRFINDERPLUS_RUN":
    amrfinderplus: 3.11.18
    amrfinderplus-database: 2023-04-17.1
"BACTOPIA:MLST:MLST_MODULE":
    mlst: 2.23.0
    mlst-database: 2.23.0-20230421
"BACTOPIA:SKETCHER:SKETCHER_MODULE":
    mash: 2.3
    sourmash: /home/jlvillanueva/.local/lib/python3.10/site-packages/scipy/__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.0 warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}" 4.8.4
"BACTOPIA:ASSEMBLER:ASSEMBLER_MODULE":
    any2fasta: 0.4.2
    assembly-scan: 1.0.0
    bwa: 0.7.17-r1188
    dragonflye: 1.1.1
    flash: 1.2.11
    flye: 2.9.2-b1786
    medaka: 1.8.0
    megahit: 1.2.9
    miniasm: 0.3-r179
    minimap2: 2.26-r1175
    nanoq: 0.10.0
    pigz: 2.6
    pilon: 1.24
    racon: 1.5.0
    rasusa: 0.7.1
    raven: 1.8.3
    samclip: 0.4.0
    samtools: 1.17
    shovill: 1.1.0
    shovill-se: 1.1.0
    skesa: 2.4.0
    spades.py: 3.15.5
    velvetg: 1.2.10
    velveth: 1.2.10
    unicycler: 0.5.0
"BACTOPIA:ANNOTATOR:PROKKA_MODULE":
    makeblastdb: 2.14.1+
    prokka: 1.14.6
```

**Comment by rpetit3** [comment] 2023-10-03 14:18
@egenomics thank you for posting this, interesting it's on a different tool. I'll get this fixed in my dev version today. Will update soon!

**Comment by rpetit3** [comment] 2023-10-03 16:02
@egenomics figured out the problem on your end. For what ever reason Conda used an older version of SciPy (<1.8) with a newer version of NumPy (>1.23). Which caused a warning to be printed. This is fixed in my dev build: https://github.com/bactopia/bactopia/commit/1cfeff1aa1db307c5754dc286cc835b96c5de5b7

@cs-di05 I will need your help. I'd like to compare your conda environment with mine to see what is causing the issue. Can you share the following?

```
conda activate /home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4/
conda env export
```

**Comment by cs-di05** [comment] 2023-10-03 18:49
Will do! Currently on vacation but next week I will respond. Best regards,
Cas

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by cs-di05** [comment] 2023-10-13 07:59
Hi Robert, this is what my environment looks like:
```
name: /home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.10=hd590300_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - art=2016.06.05=he1d7d6f_6
  - bactopia-gather=1.0.4=hdfd78af_0
  - bbmap=39.01=h92535d8_1
  - biopython=1.77=py39h27cfd23_0
  - brotli-python=1.1.0=py39hc10206b_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.16.0=h0c91306_1017
  - capnproto=0.9.1=ha19adfc_4
  - certifi=2023.7.22=pyhd8ed1ab_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - coloredlogs=15.0.1=pyhd8ed1ab_3
  - coreutils=9.4=hd590300_0
  - curl=8.3.0=hca28451_0
  - executor=23.2=pyhd3deb0d_0
  - expat=2.5.0=hcb278e6_1
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fastq-dl=2.0.4=pyhdfd78af_0
  - fastq-scan=1.0.1=h4ac6f70_2
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - gdbm=1.18=h0a1914f_2
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h0b41bf4_3
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.6=he838d99_2
  - harfbuzz=8.2.1=h3d44ed6_0
  - htslib=1.17=h81da01d_2
  - humanfriendly=10.0=py39h4162558_4
  - icu=73.2=h59595ed_0
  - idna=3.4=pyhd8ed1ab_0
  - jq=1.6=h36c2ea0_1000
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - lcms2=2.15=hb7c19ff_3
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=18_linux64_openblas
  - libcblas=3.9.0=18_linux64_openblas
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.3.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_2
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=18_linux64_openblas
  - libnghttp2=1.52.0=h61bc06f_0
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libsqlite=3.43.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.6.0=ha9c0a0a_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.11.5=h232c23b_1
  - libxslt=1.1.37=h0054252_1
  - libzlib=1.2.13=hd590300_5
  - lxml=4.9.3=py39h40bd5d0_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - mash=2.3=he348c14_1
  - mdurl=0.1.0=pyhd8ed1ab_0
  - ncbi-genome-download=0.3.3=pyh7cba7a3_0
  - ncbi-vdb=3.0.8=hdbdd923_0
  - ncurses=6.4=hcb278e6_0
  - numpy=1.26.0=py39h6dedee3_0
  - oniguruma=6.9.8=h166bdaf_0
  - openjdk=20.0.2=haa376d0_2
  - openssl=3.1.3=hd590300_0
  - ossuuid=1.6.2=hf484d3e_1000
  - pandas=2.0.3=py39h5b8634a_1
  - pbzip2=1.1.13=0
  - pcre2=10.40=hc3806b6_0
  - perl=5.22.0.1=0
  - perl-threaded=5.32.1=hdfd78af_1
  - perl-uri=1.71=pl5.22.0_1
  - perl-xml-libxml=2.0124=0
  - perl-xml-namespacesupport=1.11=0
  - perl-xml-sax=0.99=0
  - perl-xml-sax-base=1.08=0
  - pigz=2.6=h27826a3_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - property-manager=3.0=py_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pygments=2.16.1=pyhd8ed1ab_0
  - pypy3.9=7.3.12=h9557127_5
  - pysocks=1.7.1=pyha2e5f31_6
  - pysradb=2.2.0=pyhdfd78af_0
  - python=3.9.17=0_73_pypy
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.9=4_pypy39_pp73
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - rename=1.601=hdfd78af_1
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-ftp=0.3.1=py_1
  - rich=13.5.3=pyhd8ed1ab_0
  - rich-click=1.6.1=pyhd8ed1ab_0
  - samtools=1.17=hd87286a_2
  - sed=4.8=he412f7d_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.43.0=h2c6b66d_0
  - sra-tools=3.0.8=h9f5acd7_0
  - tk=8.6.13=h2797004_0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=2.0.5=pyhd8ed1ab_0
  - verboselogs=1.7=py_0
  - wget=1.20.3=ha35d2d1_1
  - wheel=0.41.2=pyhd8ed1ab_0
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
prefix: /home/cas/.bactopia/conda/bioconda--bactopia-gather-1.0.4

```

**Closed** 2024-04-04 04:40 UTC
Labels: question
