### ISSUE TITLE
[bug]GATHER_SAMPLE BUILD PROBLEM

### ISSUE THREAD

**Issue by minhtrung1997** [bactopia/bactopia#263] opened 2021-12-18 15:27 UTC
**Description**
When I use bactopia , I encounter an err of building gather _sample .2.0.x. 

**Steps to Reproduce**
`$bactopia-build.py '/home/kt/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/'  gather_assembles --verbose 2>&1| tee -a bactopia_error.log`

which I trace back error
2021-12-18 10:13:59:root:STDERR - 
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/kt/anaconda3/envs/bactopia/lib/python3.7/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/home/kt/anaconda3/envs/bactopia/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/kt/anaconda3/envs/bactopia/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/kt/anaconda3/envs/bactopia/lib/python3.7/site-packages/mamba/mamba_env.py", line 73, in mamba_install
        context.verbosity)
    mamba.mamba_api.MambaNativeException: Encountered problems while solving.
    Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by kaleido-core-0.2.1-h3644ca4_0
    Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by kaleido-core-0.2.1-h3644ca4_0
    Problem: nothing provides __glibc >=2.17,<3.0.a0 needed by kaleido-core-0.1.0-h3644ca4_0
I install bactopia through mamba in python 3,8 environment. Below is the full err log file. Please help recommendation
[bactopia_error.log](https://github.com/bactopia/bactopia/files/7739467/bactopia_error.log)

**Comment by rpetit3** [comment] 2021-12-19 01:52
Hi @minhtrung1997 

Let's see if we can get this figured out! This looks similar to https://github.com/bactopia/bactopia/issues/255. What does your `base` environment look like?

Also, can you by chance use docker or singularity?

**Comment by sepidehalamouti** [comment] 2021-12-19 03:28
Hi Robert,
I installed bactopia on a new Ubuntu system and fresh Conda and still getting error on **gather_sample** and **unfinished build on the prefix path**.

bactopia --use_ena --accession SRX4563634 --datasets datasets/ --species "Staphylococcus aureus" --coverage 100 --genome_size median --outdir ena-single-sample --cpus $(getconf _NPROCESSORS_ONLN)
2021-12-18 21:15:26:root:INFO - Found /home/ubuntu/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/annotate_genome.yml (1 of 7), begin build to /home/ubuntu/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/annotate_genome-2.0.x

External command failed with exit code 1!

Command:
bash -c 'mamba env create -f /home/ubuntu/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/annotate_genome.yml --prefix /home/ubuntu/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/annotate_genome-2.0.x --force'

Standard error:
Traceback (most recent call last):
File "/home/ubuntu/anaconda3/envs/bactopia/bin/mamba", line 7, in
from mamba.mamba import main
File "/home/ubuntu/anaconda3/envs/bactopia/lib/python3.7/site-packages/mamba/mamba.py", line 53, in
from mamba.utils import get_index, to_package_record_from_subjson, _supplement_index_with_system
File "/home/ubuntu/anaconda3/envs/bactopia/lib/python3.7/site-packages/mamba/utils.py", line 7, in
from .FastSubdirData import FastSubdirData
File "/home/ubuntu/anaconda3/envs/bactopia/lib/python3.7/site-packages/mamba/FastSubdirData.py", line 23, in
from conda._vendor.auxlib.ish import dals
ModuleNotFoundError: No module named 'conda._vendor.auxlib'

**Error executing process > 'BACTOPIA:GATHER_SAMPLES (SRX4563634)'**

Caused by:
Conda prefix path does not exist or it's not a directory: /home/ubuntu/anaconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/gather_samples-2.0.

Here is my fresh conda info:
conda info

 active environment : None
        shell level : 0
   user config file : /home/ubuntu/.condarc
populated config files :
conda version : 4.11.0
conda-build version : 3.21.5
python version : 3.9.7.final.0
virtual packages : __linux=5.4.0=0
__glibc=2.31=0
__unix=0=0
__archspec=1=x86_64
base environment : /home/ubuntu/anaconda3 (writable)
conda av data dir : /home/ubuntu/anaconda3/etc/conda
conda av metadata url : None
channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/linux-64
https://repo.anaconda.com/pkgs/r/noarch
package cache : /home/ubuntu/anaconda3/pkgs
/home/ubuntu/.conda/pkgs
envs directories : /home/ubuntu/anaconda3/envs
/home/ubuntu/.conda/envs
platform : linux-64
user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Linux/5.4.0-1008-ibm ubuntu/20.04.3 glibc/2.31
UID:GID : 1000:1000
netrc file : None
offline mode : False

**Comment by minhtrung1997** [comment] 2021-12-21 03:18
any way, I run in docker and it solves the issue. Thank you very much.

**Comment by rpetit3** [comment] 2021-12-21 04:28
Great glad its working for you! Going to close this for now

**Closed by rpetit3** 2021-12-21 04:28 UTC
Labels: bug
