### ISSUE TITLE
WhatsGNU

### ISSUE THREAD

**Issue by kusandeep** [bactopia/bactopia#162] opened 2020-12-03 21:52 UTC
**Related To**

- [ ] Bactopia Tools

Could be an nice addition to Bactopia tool.
https://github.com/ahmedmagds/WhatsGNU

**Comment by rpetit3** [comment] 2020-12-04 00:41
I agree! Going to close this one since its a duplicate of https://github.com/bactopia/bactopia/issues/111 Thank you very much for the suggestion!

**Closed by rpetit3** 2020-12-04 00:41 UTC
Labels: enhancement
