### ISSUE TITLE
[bug] quast workflow fails

### ISSUE THREAD

**Issue by egenomics** [bactopia/bactopia#457] opened 2023-10-04 14:07 UTC
**Description**
I am having some issues with the QUAST workflow, others like genotyphi or mashtree work without problems.
problem -> the QUAST workflow fails
**Steps to Reproduce**
```
conda activate bactopia-v3
wf=quast
bactopia --wf $wf \
  --bactopia /home/jlvillanueva/Documents/SALMONELLA/bactopia_v3_results \ 
  --include includes.txt --max_cpus 4 \
  -qs 2
```

**Expected Behavior**
A description of what is expected to happen.

**Execution Environment**

- Bactopia Version: 3.0.0
- OS: Ubuntu
- Environment: conda

**Additional Information**
  ```
  Bactopia Tools: `quast Execution Summary
    ---------------------------
    Bactopia Version : 3.0.0
    Nextflow Version : 23.04.3
    Command Line     : nextflow run /home/jlvillanueva/miniconda3/envs/bactopia-v3//share/bactopia-3.0.0/main.nf -w /home/jlvillanueva/Documents/SALMONELLA/scripts/work/ --wf quast --bactopia /home/jlvillanueva/Documents/SALMONELLA/bactopia_v3_results ' '
    Resumed          : false
    Completed At     : 2023-10-04T16:01:25.164277428+02:00
    Duration         : 40s
    Success          : false
    Exit Code        : 2
    Error Report     : Error executing process > 'BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL3-275_S21_L001)'

Caused by:
  Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL3-275_S21_L001)` terminated with an error exit status (2)

Command executed:

executor >  local (23)
[4f/692794] process > BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL2-995_S16_L001) [ 81%] 22 of 27, failed: 22, retries: 21
[-        ] process > BACTOPIATOOLS:QUAST:CSVTK_CONCAT                           -
[-        ] process > BACTOPIATOOLS:CUSTOM_DUMPSOFTWAREVERSIONS                  -
[9a/d32748] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL3-275_S21_L001)` terminated with an error exit status (2) -- Execution is retried (1)
[af/433727] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL2-995_S16_L001)` terminated with an error exit status (2) -- Execution is retried (1)
[a4/ceccb4] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL4-510_S22_L001)` terminated with an error exit status (2) -- Execution is retried (1)
[b2/fe73be] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL7-614_S18_L001)` terminated with an error exit status (2) -- Execution is retried (1)
[b9/4111a1] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL6-450_S23_L001)` terminated with an error exit status (2) -- Execution is retried (1)
[8e/16cd4c] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL5-311_S17_L001)` terminated with an error exit status (2) -- Execution is retried (1)
[67/0e04cd] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL1-598_S15_L001)` terminated with an error exit status (2) -- Execution is retried (1)
[28/11c549] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL3-275_S21_L001)` terminated with an error exit status (2) -- Execution is retried (2)
[f9/62e89f] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL2-995_S16_L001)` terminated with an error exit status (2) -- Execution is retried (2)
[6a/2bf474] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL4-510_S22_L001)` terminated with an error exit status (2) -- Execution is retried (2)
[e4/bb885a] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL7-614_S18_L001)` terminated with an error exit status (2) -- Execution is retried (2)
[c0/6deb07] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL6-450_S23_L001)` terminated with an error exit status (2) -- Execution is retried (2)
[3c/05c8ec] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL5-311_S17_L001)` terminated with an error exit status (2) -- Execution is retried (2)
[e8/b8ac73] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL1-598_S15_L001)` terminated with an error exit status (2) -- Execution is retried (2)
[20/d409d7] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL3-275_S21_L001)` terminated with an error exit status (2) -- Execution is retried (3)
[18/a9cb64] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL2-995_S16_L001)` terminated with an error exit status (2) -- Execution is retried (3)
[12/cc93c7] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL4-510_S22_L001)` terminated with an error exit status (2) -- Execution is retried (3)
[1e/9c6c0d] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL7-614_S18_L001)` terminated with an error exit status (2) -- Execution is retried (3)
[4d/3cc26e] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL6-450_S23_L001)` terminated with an error exit status (2) -- Execution is retried (3)
[98/e9e901] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL5-311_S17_L001)` terminated with an error exit status (2) -- Execution is retried (3)
[7a/acbfdc] NOTE: Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL1-598_S15_L001)` terminated with an error exit status (2) -- Execution is retried (3)
ERROR ~ Error executing process > 'BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL3-275_S21_L001)'

Caused by:
  Process `BACTOPIATOOLS:QUAST:QUAST_MODULE (20591-SAL3-275_S21_L001)` terminated with an error exit status (2)

Command executed:

  if [ "true" == "true" ]; then
      gzip -c -d 20591-SAL3-275_S21_L001.fna.gz > 20591-SAL3-275_S21_L001.fna
  fi
  
  est_ref_size=$(tail -n 1 20591-SAL3-275_S21_L001-meta.tsv | cut -f 7)
  if [ "${est_ref_size}" != "0" ]; then
      est_ref_size="--est-ref-size ${est_ref_size}"
  fi
  
  quast 20591-SAL3-275_S21_L001.fna ${est_ref_size} \
      -o results \
      --threads 4 \
      --contig-thresholds '0,1000,10000,100000,250000,1000000' --plots-format pdf \
      --glimmer
  
  mv results/quast.log ./
  mv results/transposed_report.tsv results/20591-SAL3-275_S21_L001.tsv
  
  cat <<-END_VERSIONS > versions.yml
  "BACTOPIATOOLS:QUAST:QUAST_MODULE":
      quast: $(quast --version 2>&1 | sed 's/^.*QUAST v//; s/ .*$//')
  END_VERSIONS

Command exit status:
  2

Command output:
  (empty)

Command error:
  ERROR! File not found (contigs): 0
  
  In case you have troubles running QUAST, you can write to quast.support@cab.spbu.ru
  or report an issue on our GitHub repository https://github.com/ablab/quast/issues
  Please provide us with quast.log file from the output directory.

Work dir:
  /home/jlvillanueva/Documents/SALMONELLA/scripts/work/7c/401314c0517f3d4b934b3a0ae667d5

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details
```

**Comment by egenomics** [comment] 2023-10-04 15:00
I also get a similar error using -profile singularity

**Comment by rpetit3** [comment] 2023-10-04 15:19
Thank you for sharing, let me see if I can replicate on my end using singularity. Will update shortly

**Comment by rpetit3** [comment] 2023-10-04 15:41
Bummer! 

```
executor >  local (3)
[92/ef2ea8] process > BACTOPIATOOLS:QUAST:QUAST_MODULE (SRR2838702) [100%] 1 of 1 ✔
[b2/59467b] process > BACTOPIATOOLS:QUAST:CSVTK_CONCAT (quast)      [100%] 1 of 1 ✔
[af/b64d29] process > BACTOPIATOOLS:CUSTOM_DUMPSOFTWAREVERSIONS (1) [100%] 1 of 1 ✔

    Bactopia Tools: `quast Execution Summary
    ---------------------------
    Bactopia Version : 3.0.1
    Nextflow Version : 23.04.3
    Command Line     : nextflow run /home/robert_petit/miniconda3/envs/bactopia-dev//share/bactopia-3.0.1/main.nf -w /home/robert_petit/temp/bactopia-dev/work/ --wf quast --bactopia bactopia/ -profile singularity
    Resumed          : false
    Completed At     : 2023-10-04T15:40:18.126506600Z
    Duration         : 16s
    Success          : true
    Exit Code        : 0
    Error Report     : -
    Launch Dir       : /home/robert_petit/temp/bactopia-dev
```

Can you by chance share the quality of the assemblies from assembly-scan, or share some inputs with me to test on my end?

**Comment by egenomics** [comment] 2023-10-06 14:02
Sure, I just sent you an email to your gmail account.

**Comment by egenomics** [comment] 2023-10-19 14:04
Did you manage to reproduce the issue?

**Comment by rpetit3** [comment] 2023-10-19 16:19
Thank you for the reminder, just gave it a try using Conda. Unfortunately I'm not able to reproduce the error, QUAST finishes fine on the sample sent to me.

COuld you perhaps share the logs files associated with these failures?

**Comment by egenomics** [comment] 2023-10-20 11:14
That's great! 
I just send you an email with the relevant files.

**Comment by Kokejuli** [comment] 2024-03-06 11:38
Hey @rpetit3 , I had a similar error. The problem that I see here is when ${est_ref_size} is equals to 0 (for example when it is run bactopia prepare without any species indicated). In this case, ${est_ref_size} is just 0 and does not include the flag (--est-ref-size). As we are running a command like:

```
quast 20591-SAL3-275_S21_L001.fna 0 \
    -o results \
    --threads 4 \
    --contig-thresholds '0,1000,10000,100000,250000,1000000' --plots-format pdf \
    --glimmer
```

Quast returns an error, saying 0 is not a valid argument

I hope this can be useful. Thank you very much for this awesome tool!

**Comment by rpetit3** [comment] 2024-03-06 18:25
@Kokejuli thank you for bringing this to my attention! This should now hopefully be fixed in the dev version: https://github.com/bactopia/bactopia/commit/467d6d3789535e942ec32355bc92d095ae9c6a44

Will be available in the next release

**Comment by rpetit3** [comment] 2024-04-04 03:19
Hi All,

I've release [Bactopia v3.0.1](https://bactopia.github.io/latest/changelog/#v301-bactopiabactopia-thats-my-girl-20240325). Since I had previously marked this as "fixed" (haha my reminder to close after the next release!), I will go ahead and close this, please feel free to reopen if you think it should still be open.

Also, it would be super useful if took the time to complete my [2024 Bactopia Usage Survey](https://forms.gle/BA2BDHRQvZtpVcD38). 

Thank you so much!
Robert

**Closed by rpetit3** 2024-04-04 03:19 UTC
Labels: bug, fixed
