### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by marcelladane** [bactopia/bactopia#143] opened 2020-10-08 19:47 UTC
Hello guys, I am trying to run the tutorial to check if the installation was correct (and while I am waiting for the real data to run on it). 

First, I noticed that if I don´t specify "--outdir" here it doesn´t work:
bactopia datasets datasets/ --ariba "vfdb_core,card" \
                            --species "Staphylococcus aureus" \
                            --include_genus \
                            --cpus 4
It is not a big deal, but since it is a tutorial, I thought you would like to add the info needed to run it easily....

But my other problem is more serious. I can´t run your dataset, I get the following error: 
 Bactopia Execution Summary
    ---------------------------
    Command Line    : nextflow run /home/marcellap/miniconda3/envs/bactopia//share/bactopia-1.4.x/main.nf --accession SRX4563634 --datasets bactopia-tutorial/datasets/ --species 'Staphylococcus aureus' --coverage 100 --genome_size median --cpus 2 --outdir ena-single-sample
    Resumed         : false

    Completed At    : 2020-10-08T21:23:50.420595+02:00
    Duration        : 1h 16m 4s
    Success         : false
    Exit Code       : 1
    Error Report    : Error executing process > 'call_variants (SRX4563634 - GCF_000009645)'

Caused by:
  Process `call_variants (SRX4563634 - GCF_000009645)` terminated with an error exit status (1)

Command executed [/home/marcellap/miniconda3/envs/bactopia/share/bactopia-1.4.x/templates/call_variants.sh]:

  #!/bin/bash
  set -e
  set -u

  LOG_DIR="call_variants"
  if [ "false" == "true" ]; then
      mkdir GCF_000009645
      touch GCF_000009645/call_variants.dry_run.txt
  else
      mkdir -p ${LOG_DIR}
      echo "# Timestamp" > ${LOG_DIR}/call_variants.versions
      date --iso-8601=seconds >> ${LOG_DIR}/call_variants.versions
      echo "# Snippy Version" >> ${LOG_DIR}/call_variants.versions
      snippy --version >> ${LOG_DIR}/call_variants.versions 2>&1

      snippy --R1 SRX4563634_R1.fastq.gz --R2 SRX4563634_R2.fastq.gz \
          --ref GCF_000009645.gbff \
          --cpus 2 \
          --ram 15.8 \
          --outdir GCF_000009645 \
          --prefix SRX4563634 \
          --mapqual 60 \
          --basequal 13 \
          --mincov 10 \
          --minfrac 0 \
          --minqual 100 \
          --maxsoft 10   > ${LOG_DIR}/snippy.out 2> ${LOG_DIR}/snippy.err

      # Add GenBank annotations
      echo "# vcf-annotator Version" >> ${LOG_DIR}/call_variants.versions
      vcf-annotator --version >> ${LOG_DIR}/call_variants.versions 2>&1
      vcf-annotator GCF_000009645/SRX4563634.vcf GCF_000009645.gbff > GCF_000009645/SRX4563634.annotated.vcf 2> ${LOG_DIR}/vcf-annotator.err

      # Get per-base coverage
      echo "# bedtools Version" >> ${LOG_DIR}/call_variants.versions
      bedtools --version >> ${LOG_DIR}/call_variants.versions 2>&1
      grep "^##contig" GCF_000009645/SRX4563634.vcf > GCF_000009645/SRX4563634.full-coverage.txt
      genomeCoverageBed -ibam GCF_000009645/SRX4563634.bam -d >> GCF_000009645/SRX4563634.full-coverage.txt 2> ${LOG_DIR}/genomeCoverageBed.err
      cleanup-coverage.py GCF_000009645/SRX4563634.full-coverage.txt > GCF_000009645/SRX4563634.coverage.txt
      rm GCF_000009645/SRX4563634.full-coverage.txt

      # Mask low coverage regions
      mask-consensus.py SRX4563634 GCF_000009645 \
                        GCF_000009645/SRX4563634.consensus.subs.fa \
                        GCF_000009645/SRX4563634.subs.vcf \
                        GCF_000009645/SRX4563634.coverage.txt \
                        --mincov 10 > GCF_000009645/SRX4563634.consensus.subs.masked.fa 2> ${LOG_DIR}/mask-consensus.err

      # Clean Up
      rm -rf GCF_000009645/reference GCF_000009645/ref.fa* GCF_000009645/SRX4563634.vcf.gz*

      if [[ false == "true" ]]; then
          find GCF_000009645/ -type f -not -name "*.bam*" -and -not -name "*.log*" -and -not -name "*.txt*" | \
              xargs -I {} pigz -n --best -p 2 {}
          pigz -n --best -p 2 GCF_000009645/SRX4563634.coverage.txt
      fi

      if [ "false" == "false" ]; then
          cp .command.err ${LOG_DIR}/call_variants.err
          cp .command.out ${LOG_DIR}/call_variants.out
          cp .command.sh ${LOG_DIR}/call_variants.sh || :
          cp .command.trace ${LOG_DIR}/call_variants.trace || :
      else
          rm -rf ${LOG_DIR}/
      fi
  fi

Command exit status:
  1

Command output:
  (empty)

Work dir:
  /home/marcellap/bactopia/work/a7/52dfddabf599066865ba4eaf067a98

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

    Launch Dir      : /home/marcellap/bactopia
    Working Dir     : /home/marcellap/bactopia/work (Total Size: 11.53G)
    Working Dir Size: 11.53G

WARN: Killing pending tasks (1)

I am using Linux subsystem in windows 10 and installed the package using conda. 

Can you please give me an idea for the possible source of problem?

**Comment by rpetit3** [comment] 2020-10-08 20:58
@marcelladane I think this is a duplicate of https://github.com/bactopia/bactopia/issues/142 feel free to reopen if not

**Closed by rpetit3** 2020-10-08 20:58 UTC
Labels: bug
