### ISSUE TITLE
gather_samples does not exist with previou[bug]

### ISSUE THREAD

**Issue by callaband** [bactopia/bactopia#268] opened 2021-12-29 08:33 UTC
**Description**
Just updated my bactopia (conda update bactopia) from 1.7.0 to 2.0.0 and now I get an error at the start of the run (gather samples) - 'Conda prefix path does not exist or it's not a directory: /home/user/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/gather_samples-2.0.x' 

When I look into it, that is true, it looks like the new path should be '/home/user/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/linux/gather_samples.md5/yml/Dockerfile'. The prefix I provided was right, but it looks like the full path is not. 

**Steps to Reproduce**
```
bactopia --fastqs /home/user/path/fofn.txt --outdir /home/user/path/Bactopia_AZ20 --nfconfig /home/user/path/config_bactopia_pbs.txt --datasets /home/user/path/datasets --species 'Escherichia coli' --compress --run_name bactopia-AZ20

Error executing process > 'BACTOPIA:GATHER_SAMPLES (Sample_name)'
Caused by:
Conda prefix path does not exist or it's not a directory: /home/user/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/gather_samples-2.0.x
[this repeats a second time]
```

**Expected Behavior**
Expected workflow run

**Execution Environment**

- Bactopia Version: 2.0.0
- OS: Linux 
- Environment: conda

**Additional Information**
in config file, conda = '/home/user/miniconda3/envs/bactopia'
Tried installing bactopia fresh into a new environment and encountered the exact same issue.

**Comment by rpetit3** [comment] 2021-12-29 15:22
Hi @callaband! Are you running this on a cluster?

**Comment by callaband** [comment] 2021-12-29 19:01
Yes

**Comment by rpetit3** [comment] 2021-12-29 20:24
Can you use singularity or docker on your cluster?

I'm wondering if when the job is run on a worker node it no longer has access to `/home/user/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/gather_samples-2.0.x`

**Comment by callaband** [comment] 2021-12-30 04:35
It doesn't look like it - "docker --version" and "singularity version" results in "command not found". I am not an administrator, so it seems like I will not be able to easily add them. If using that would solve the issue, I can talk to my administrator next week about adding them and/or installing bactopia centrally as a conda module. 

Perhaps, the only directories I see in /home/user/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/ are "linux" and "mac". There is no "envs" so I'm not sure about losing access, if it doesn't exist?

**Comment by Jamesped** [comment] 2021-12-30 13:25
Similar issue for me. Bactopia worked well in 1.7.0 but always failed in the steps of 'ASSEMBLE_GENOME' and 'ARIBA_ANALYSIS' in 2.0.0. 
I worked in the conda environment in a macOSX machine.  

Error executing process > 'BACTOPIA:ASSEMBLE_GENOME (SRX)'

Caused by:
  Process `BACTOPIA:ASSEMBLE_GENOME (SRX)` terminated with an error exit status (127)

**Comment by rpetit3** [comment] 2022-01-02 08:21
@callaband 

_It doesn't look like it - "docker --version" and "singularity version" results in "command not found". I am not an administrator, so it seems like I will not be able to easily add them. If using that would solve the issue, I can talk to my administrator next week about adding them and/or installing bactopia centrally as a conda module._ 

I think on clusters Singularity or Docker should be preferred, mostly to avoid conda related issues.


Can you verify you have access to `/home/user/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/` on a worker node?

**Comment by callaband** [comment] 2022-01-03 21:00
So I guess I'm working on a grid, not a cluster. System admin says docker/singularity are not appropriate for our set-up. 

I have access to /home/user/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/. I do not have access to /home/user/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/ - the envs folder does not exist (linux and mac sub-directories exist within the conda directory). 

I have tried running my script using Bactopia ver 1.6, 1.7, and 2.0 now and consistently get the same error 
> Conda prefix path does not exist or it's not a directory: /home/user/miniconda3/envs/bactopia-1.6/share/bactopia-1.6.x/conda/envs/gather_fastqs-1.6.x
> Conda prefix path does not exist or it's not a directory: /home/user/miniconda3/envs/bactopia-1.7/share/bactopia-1.7.x/conda/envs/gather_fastqs-1.7.x 
> Conda prefix path does not exist or it's not a directory: /home/user/miniconda3/envs/bactopia/share/bactopia-2.0.x/conda/envs/gather_fastqs-2.0.x

**Comment by rpetit3** [comment] 2022-01-03 21:21
Is there anything in `--nfconfig /home/user/path/config_bactopia_pbs.txt` that might affect things?

**Comment by callaband** [comment] 2022-01-03 22:53
Maybe the conda path? But it looks accurate. This is what it contains:
`process {
   executor = 'pbs'
   queue = 'med8gb'
   clusterOptions = '-l nodes=1:ppn=8,mem=8gb,walltime=4:00:00'
   conda = '/home/user/miniconda3/envs/bactopia'
   
   withLabel: assemble_genome {
   queue = 'longmem'
   clusterOptions = '-l nodes=1:ppn=12,mem=50gb,walltime=24:00:00'
   }
}`

**Comment by rpetit3** [comment] 2022-01-03 22:59
I know the issue! Its because `--nfconfig` was used, so it skips the auto build step.

You will need run `bactopia build --default`, then I think its should build everything for you.

**Comment by callaband** [comment] 2022-01-05 01:09
Yes, that's it - Thank you so much!

**Comment by rpetit3** [comment] 2022-01-05 01:37
Great glad you are moving again! I'm going to be revamping the `bactopia build` process in the near future.

Going to close this for now, please feel free to reopen, and if you ever have any feedback or suggestions please share!

**Closed by rpetit3** 2022-01-05 01:37 UTC
Labels: bug
