### ISSUE TITLE
BLAST Failing with FOFN input

### ISSUE THREAD

**Issue by andriesfeder** [bactopia/bactopia#195] opened 2021-03-01 19:55 UTC
When I run Bactopia on multiple samples using a FOFN file, BLAST against the PLSDB fails. I haven't had that issue when using Bactopia one sample at a time.  Here is the call that has been causing this issue and I've attached a FOFN similar to the one I'm trying to use.

` $ bactopia --fastqs fastqs.txt \
             --datasets bactopia/datasets/ \
             --species "Staphylococcus aureus" \
             --coverage 40 \
             --cleanup_workdir \
             --cpus 4 \
             --outdir local-multiple-samples
`
I haven't had any issues with this while using Bactopia with a single sample.  Any help would be appreciated!

[fastqs.txt](https://github.com/bactopia/bactopia/files/6064101/fastqs.txt)

**Comment by rpetit3** [comment] 2021-03-01 20:02
Well that's a weird one! What version of bactopia are you using? (`bactopia --version`)

**Comment by andriesfeder** [comment] 2021-03-01 20:04
I'm using bactopia 1.6.1

Really am not sure why this would be happening!

**Comment by rpetit3** [comment] 2021-03-01 20:08
Going to try and reproduce locally.

Is it giving a specific error message?

**Comment by andriesfeder** [comment] 2021-03-01 20:11
It is not beyond:

'NOTE: Process `plasmid_blast (Ho_00364)` failed -- Execution is retried (1)'

**Comment by rpetit3** [comment] 2021-03-01 20:56
Haha, not the most helpful huh?

Looking into it now

**Comment by rpetit3** [comment] 2021-03-01 22:47
Hmmm, I was unable to replicate. Here's what I did:

```
conda create -y -n bactopia-1.6.1 -c conda-forge -c bioconda bactopia
conda activate bactopia-1.6.1
bactopia --version
bactopia 1.6.1

# Create test dir
mkdir test-plsdb
cd test-plsdb/

# build datasets
bactopia datasets --species 'Staphylococcus aureus'
... text ...
2021-03-01 16:17:30:root:INFO - Setting up pre-computed PLSDB (plasmids) datasets
... text ...
2021-03-01 16:33:54:root:INFO - Writing summary of available datasets

# Check PLSDB
ls -lh datasets/plasmid/
total 958M
-rw-r--r-- 1 rpetit users  33M Dec 16 16:35 plsdb.abr
-rw-r--r-- 1 rpetit users 1.2M Dec 16 16:35 plsdb_changes.tsv
-rw-r--r-- 1 rpetit users 4.0M Dec 16 16:35 plsdb.fna.nhr
-rw-r--r-- 1 rpetit users 328K Dec 16 16:35 plsdb.fna.nin
-rw-r--r-- 1 rpetit users 683M Dec 16 16:35 plsdb.fna.nsq
-rw-r--r-- 1 rpetit users 217M Dec 16 16:35 plsdb.msh
-rw-r--r-- 1 rpetit users  144 Mar  1 16:18 plsdb-orginal-names.txt
-rw-r--r-- 1 rpetit users 1.8M Dec 16 16:35 plsdb.sim
-rw-r--r-- 1 rpetit users  18M Dec 16 16:35 plsdb.tsv
-rw-r--r-- 1 rpetit users   21 Mar  1 16:18 plsdb-updated.txt
-rw-rw-rw- 1 rpetit users  13K Dec 16 16:18 README.md

# Move datasets to match 
mkdir bactopia
mv datasets/ bactopia/

# prepare fofn
bactopia prepare ../test-20-samples/ -r | head -n 5 > fastqs.txt
cat fastqs.txt
sample  runtype r1      r2      extra
ERX140798       paired-end      /local/home/rpetit/bactopia-dev/test-20-samples/ERX140798/quality-control/ERX140798_R1.fastq.gz /local/home/rpetit/bactopia-dev/test-20-samples/ERX140798/quality-control/ERX140798_R2.fastq.gz
ERX1666543      paired-end      /local/home/rpetit/bactopia-dev/test-20-samples/ERX1666543/quality-control/ERX1666543_R1.fastq.gz       /local/home/rpetit/bactopia-dev/test-20-samples/ERX1666543/quality-control/ERX1666543_R2.fastq.gz
ERX1711341      paired-end      /local/home/rpetit/bactopia-dev/test-20-samples/ERX1711341/quality-control/ERX1711341_R1.fastq.gz       /local/home/rpetit/bactopia-dev/test-20-samples/ERX1711341/quality-control/ERX1711341_R2.fastq.gz
ERX1830501      paired-end      /local/home/rpetit/bactopia-dev/test-20-samples/ERX1830501/quality-control/ERX1830501_R1.fastq.gz       /local/home/rpetit/bactopia-dev/test-20-samples/ERX1830501/quality-control/ERX1830501_R2.fastq.gz

# Run bactopia
bactopia --fastqs fastqs.txt --datasets bactopia/datasets/ --species "Staphylococcus aureus" --coverage 40 --cleanup_workdir --cpus 4 --outdir local-multiple-samples
Found Conda environments in /local/home/rpetit/miniconda3/envs/bactopia-1.6.1/share/bactopia-1.6.x/conda/envs, if a complete rebuild is needed please use --force
N E X T F L O W  ~  version 20.10.0
Launching `/local/home/rpetit/miniconda3/envs/bactopia-1.6.1/share/bactopia-1.6.x/main.nf` [naughty_shannon] - revision: 0ccba37f01
bactopia - 1.6.1

Each task will use 4 CPUs out of the available 72 CPUs. At most 18 task(s) will be run at
a time, this can affect the efficiency of Bactopia.

Found 1 Antimicrobial resistance datasets
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/antimicrobial-resistance/amrfinderdb.tar.gz
Found 2 ARIBA datasets
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/ariba/card.tar.gz
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/ariba/vfdb_core.tar.gz
Found 3 PLSDB (plasmid) BLAST files
bactopia/datasets/plasmid/plsdb.fna.nin
bactopia/datasets/plasmid/plsdb.fna.nsq
bactopia/datasets/plasmid/plsdb.fna.nhr
Found 5 minmer sketches/signatures
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/minmer/genbank-k21.json.gz
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/minmer/genbank-k31.json.gz
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/minmer/genbank-k51.json.gz
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/minmer/refseq-k21-s1000.msh
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/plasmid/plsdb.msh
Genome size will be estimated.
Found Prokka proteins file
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/species-specific/staphylococcus-aureus/annotation/proteins.faa
Found Mash Sketch of RefSeq genomes
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/species-specific/staphylococcus-aureus/minmer/refseq-genomes.msh
Found 2 MLST datasets
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/species-specific/staphylococcus-aureus/mlst/default/default-ariba.tar.gz
/local/home/rpetit/bactopia-dev/test-plsdb/bactopia/datasets/species-specific/staphylococcus-aureus/mlst/default/default-blastdb.tar.gz
If something looks wrong, now's your chance to back out (CTRL+C 3 times).
Sleeping for 5 seconds...
executor >  local (104)
[5b/5ad740] process > gather_fastqs (ERX1830501)                       [100%] 4 of 4 ✔
[a7/f03dd3] process > fastq_status (3)                                 [100%] 4 of 4 ✔
[33/726a99] process > estimate_genome_size (ERX140798)                 [100%] 4 of 4 ✔
[34/cada2e] process > qc_reads (ERX140798)                             [100%] 4 of 4 ✔
[1d/44d189] process > qc_original_summary (ERX140798)                  [100%] 4 of 4 ✔
[10/424eb6] process > qc_final_summary (ERX140798)                     [100%] 4 of 4 ✔
[96/89741b] process > assemble_genome (ERX140798)                      [100%] 4 of 4 ✔
[6c/d40cda] process > assembly_qc (ERX1830501 - checkm)                [100%] 8 of 8 ✔
[6a/c7a4a5] process > make_blastdb (ERX140798)                         [100%] 4 of 4 ✔
[98/f39863] process > annotate_genome (ERX140798)                      [100%] 4 of 4 ✔
[7b/6fc2c4] process > count_31mers (ERX140798)                         [100%] 4 of 4 ✔
[9c/cf4bd0] process > sequence_type (ERX1666543 - default - ariba)     [100%] 8 of 8 ✔
[b3/7dd24a] process > ariba_analysis (ERX1830501 - vfdb_core)          [100%] 8 of 8 ✔
[f8/75d7ee] process > minmer_sketch (ERX140798)                        [100%] 4 of 4 ✔
[8d/fc1cae] process > minmer_query (ERX140798 - refseq-k21-s1000.msh)  [100%] 20 of 20 ✔
[-        ] process > call_variants                                    -
[ea/7fbf29] process > download_references (ERX140798 - 1 reference(s)) [100%] 4 of 4 ✔
[a2/146cf7] process > call_variants_auto (ERX140798 - GCF_900475055)   [100%] 4 of 4 ✔
[d4/0ea643] process > antimicrobial_resistance (ERX140798)             [100%] 4 of 4 ✔
[4d/0849c7] process > plasmid_blast (ERX1830501)                       [100%] 4 of 4 ✔
[-        ] process > blast_genes                                      -
[-        ] process > blast_primers                                    -
[-        ] process > blast_proteins                                   -
[-        ] process > mapping_query                                    -
Completed at: 01-Mar-2021 17:40:59
Duration    : 26m 4s
CPU hours   : 14.0
Succeeded   : 104

```

Could you give the `ls -lh` output of the `bactopia/datasets/plasmid` directory? I wonder if something is going on there.

**Comment by andriesfeder** [comment] 2021-03-01 22:57
Hmm ok it definitely seems like it is something specific to my set up.  I built the dataset following the Bactopia tutorial.  Here is the output of `ls -lh`
```
total 1983928
-rw-rw-rw-  1 afeder  staff    12K Dec 16 16:18 README.md
-rw-r--r--  1 afeder  staff   144B Feb 12 14:02 plsdb-orginal-names.txt
-rw-r--r--  1 afeder  staff    21B Feb 12 14:02 plsdb-updated.txt
-rw-r--r--  1 afeder  staff    33M Dec 16 16:35 plsdb.abr
-rw-r--r--  1 afeder  staff   3.9M Dec 16 16:35 plsdb.fna.nhr
-rw-r--r--  1 afeder  staff   327K Dec 16 16:35 plsdb.fna.nin
-rw-r--r--  1 afeder  staff   683M Dec 16 16:35 plsdb.fna.nsq
-rw-r--r--  1 afeder  staff   217M Dec 16 16:35 plsdb.msh
-rw-r--r--  1 afeder  staff   1.7M Dec 16 16:35 plsdb.sim
-rw-r--r--  1 afeder  staff    18M Dec 16 16:35 plsdb.tsv
-rw-r--r--  1 afeder  staff   1.2M Dec 16 16:35 plsdb_changes.tsv
```

**Comment by rpetit3** [comment] 2021-03-01 23:18
Hmmmm, let's see if we can find in the `work` directory.

Maybe some thing like `find . -p "*plasmid_blast*"`

**Comment by andriesfeder** [comment] 2021-03-02 00:16
Ok I've found the work directory.  Anything I should be looking for?

**Comment by rpetit3** [comment] 2021-03-02 00:56
If you found one with `plasmid_blast` in it, what does the `ls -lh` look like?

**Comment by andriesfeder** [comment] 2021-03-02 15:15
Inside `plasmid_blast` `ls -lh` yields:
```total 8
-rw-r--r--  1 afeder  staff   611B Mar  1 14:06 plasmid_blast.versions 
```
One directory back I've got:
```
total 0
lrwxr-xr-x  1 afeder  staff    97B Mar  1 14:06 Ho_00364.ffn -> /Volumes/LaCie_2/Bactopia/work/bactopia/df/fa27b9a83151136edffd82376454ec/annotation/Ho_00364.ffn
drwxr-xr-x  3 afeder  staff    96B Mar  1 14:06 plasmid_blast
lrwxr-xr-x  1 afeder  staff    65B Mar  1 14:06 plsdb.fna.nhr -> /Users/afeder/Desktop/PJP/bactopia/datasets/plasmid/plsdb.fna.nhr
lrwxr-xr-x  1 afeder  staff    65B Mar  1 14:06 plsdb.fna.nin -> /Users/afeder/Desktop/PJP/bactopia/datasets/plasmid/plsdb.fna.nin
lrwxr-xr-x  1 afeder  staff    65B Mar  1 14:06 plsdb.fna.nsq -> /Users/afeder/Desktop/PJP/bactopia/datasets/plasmid/plsdb.fna.nsq
drwxr-xr-x  6 afeder  staff   192B Mar  1 15:05 temp_json
```

**Comment by rpetit3** [comment] 2021-03-02 17:37
Getting close! In this directory, there should be some nextflow files `.command.*` 

What does `.command.log` or `.command.err` look like?

**Comment by andriesfeder** [comment] 2021-03-02 18:11
Great! I really appreciate all your help with this.  I've gone through and looked at all the `.command.log` and `.command.err` in directories related to `plasmid_blast`.  They are all blank which seems odd?

**Comment by rpetit3** [comment] 2021-03-02 18:25
Haha this one is really being elusive huh?

Curious, did `Ho_00364` finish fine when it was one as a single sample?

**Comment by andriesfeder** [comment] 2021-03-02 18:26
It did, yea.

**Comment by rpetit3** [comment] 2021-03-02 18:45
Lets try in a fresh directory and remove `--cleanup_workdir`. I don't think `--cleanup_workdir` is the issue but since we're testing I'd rather keep the work directory.

Maybe something like this? (in the directory you were in)
```
mkdir plasmid-test
cd plasmid-test
bactopia --fastqs ../fastqs.txt \
         --datasets ../bactopia/datasets/ \
         --species "Staphylococcus aureus" \
         --coverage 40 \
         --cpus 4 \
         --outdir local-multiple-samples
```

What I'm hoping is with the fresh work directory, we shouldn't have to worry about some if the successful runs.

Also, what operating system are you on? I tested on Linux (Debian)

**Comment by andriesfeder** [comment] 2021-03-03 00:11
Well good news! That went off without a hitch. 

I'm on MacOS which I know is not directly supported for Bactopia (and really appreciate your help with this even though I'm not on Linux!)  I've got a computer running Ubuntu but it is cranky and I am hoping to avoid needing it.

**Comment by rpetit3** [comment] 2021-03-03 00:21
oh! that's is good news! 

I've had something similar happen in the past. (e.g. moving directories and rerunning was the solution). I've going to tag this incase something similar pops up again.

Haha I have the opposite problem then you! My old mac book is the cranky one!

I'm going to close this for now, please don't hesitate to reopen or reach out if another issue pops up.

**Closed by rpetit3** 2021-03-03 00:21 UTC
Labels: bug

**Comment by andriesfeder** [comment] 2021-03-03 01:46
Thanks so much for your help, Robert! I really appreciate it.
